### ISSUE TITLE
Problema ROAs

### ISSUE THREAD

**Issue by bruzzese95** [ThetaRangers/KatharaRPKI#1]
Ciao ragazzi,
sono interessata al vostro progetto e ho provato a farlo funzionare.
Purtroppo le prefix-table non si riempiono e non risultano ROA in Routinator.
Quale può essere il motivo?

Mi interesserebbe poterci scambiare qualche e-mail, io ho sviluppato un progetto simile al vostro.
Vi lascio il mio contatto: bruzzese.1648786@studenti.uniroma1.it

**Comment by Lorenzoval** [comment]
Ciao!
Probabilmente nel tuo caso non funziona perché il progetto dà per scontato che le immagini docker non specificate siano prese da ferrarally/frr. Questo perché è necessario installare il pacchetto frr-rpki-rtrlib nei container kathara/frr per aggiungere il supporto RPKI.
È possibile cambiare l'impostazione di default di kathara per i container nel file ~/.config/kathara.conf in modo simile:
```
...
 "image": "ferrarally/frr",
...
```

L'esecuzione per me funziona senza problemi.
Le ROA sono generate con lo script add_roas.sh invocato in [krill.startup](https://github.com/ThetaRangers/KatharaRPKI/blob/main/rpki/krill.startup).
Dopo aver eseguito il comando ```kathara lstart``` nella cartella rpki, è possibile accedere all'intefaccia web di Krill inserendo nel browser l'indirizzo https://localhost:3000. La password è NSD.
![ROAs](https://user-images.githubusercontent.com/6340681/193078550-00ad417d-39f9-4fae-9127-9d504bccb182.png)
Come si può vedere nell'immagine, le ROA sono presenti in Krill.

Le informazioni sono quindi accessibili ai vari container che eseguono Routinator.
Eseguendo un port mapping tra container Routinator (es. customer1r1) ed host simile a quello fatto per Krill in [lab.conf](https://github.com/ThetaRangers/KatharaRPKI/blob/main/rpki/lab.conf), è possibile raggiungere la sua interfaccia web all'indirizzo http://localhost:9556
![Routinator](https://user-images.githubusercontent.com/6340681/193082956-f945284a-0d88-4cb4-964e-9211e9621c73.png)
I container Routinator si connettono con successo a Krill. Gli update BGP sono infatti condivisi ed accettati ed i vari nodi possono pingarsi.
Bisogna comunque attendere un paio di minuti all'avvio della rete per aspettare che questa si configuri.

@bruzzese95 se riesci ad eseguire il tutto fammelo sapere, così posso chiudere la issue. Se incorri in qualche problematica indica bene in quale fase.

Per altre informazioni implementative non riguardanti questa issue mi puoi scrivere qui:
lorenzoval98@gmail.com

**Comment by bruzzese95** [comment]
@Lorenzoval grazie mille per la risposta dettagliata, puoi chiudere la issue.
