### ISSUE TITLE
Kathará Community Labs

### ISSUE THREAD

**Issue by tcaiazzi** [ThetaRangers/KatharaRPKI#2]
Ciao a tutti, 
sono Tommaso Caiazzi uno degli sviluppatori di Kathará. 

Il vostro laboratorio è veramente molto interessante! 

Ci farebbe veramente piacere aggiungerlo ai [lab della community](https://github.com/KatharaFramework/Kathara-Labs/wiki/Community-Labs).

Se siete interessati, potreste aggiungere i Dockerfile delle immagini e un README che spieghi in cosa cosiste il laboratorio? :innocent: 

Ciao e bravi! :rocket:

**Comment by Lorenzoval** [comment]
Ciao!
Per prima cosa ti ringraziamo dello strumento didattico che ci avete fornito.
Abbiamo modificato il laboratorio includendo il README ed i Dockerfile.
Per eventuali modifiche siamo a disposizione.

**Comment by tcaiazzi** [comment]
Ciao! 

Mi sembra perfetto!  Appena ho un attimo aggiungo il vostro lab a quelli della community :rocket: 

Ho bisogno solo di sapere cosa mettere nel campo authors :innocent: 

Ottimo lavoro e grazie mile! :smile:

**Comment by Lorenzoval** [comment]
Ecco i nostri nomi:

@Lorenzoval - Lorenzo Valeriani
@ferra-rally - Daniele Ferrarelli
@IronMarken - Marco Ferri

Grazie di nuovo!

**Comment by tcaiazzi** [comment]
Ho aggiunto il lab! 

Chiudo la issue. 

Grazie mille! :rocket:
